[build]
command = "npm install"
environment = "node"

[env]
MONGO_URI = "mongodb+srv://NandyCodes:nandykwaeza@cluster0.ibwly3i.mongodb.net/EmpowerHer?appName=Cluster0"
JWT_SECRET = "babykwaeza"
JOURNAL_SECRET = "9c91420baa2b1d30d4e1f26144e935d3ecd98306b6de21dbd420ee183f09dac6"
CLOUDINARY_CLOUD_NAME = "dnuvwdypp"
CLOUDINARY_API_KEY = "237324875837228"
CLOUDINARY_API_SECRET = "j7rYMAekp8fVkI_1RmykVg5Yans"
NODE_ENV = "production"
PORT = "5000"
FRONTEND_URL = "http://localhost:3000"

[[routes]]
path = "/*"
handler = "backend/server.js"
